a=float(input())
b=float(input())
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
age =int(input())
print(age>18)
print(age==18)
print(age<18)